#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys
import os
import time
import random
import textwrap
from datetime import datetime

# --- CONFIGURATION & STYLING ---
class Style:
    # Warna ANSI Escape Code
    HEADER = '\033[95m'  # Pink Polkadot
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
    RESET = '\033[0m'

    @staticmethod
    def print_step(step, msg):
        print(f"{Style.GREEN}[{step}]{Style.RESET} {msg}")

    @staticmethod
    def print_info(msg):
        print(f"{Style.BLUE}  ? {msg}{Style.RESET}")

class SolidityTemplates:
    """Menyimpan template kode agar main logic tetap bersih"""
    
    @staticmethod
    def get_xcm_contract(project_name, author, para_id):
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        return textwrap.dedent(f"""\
            // SPDX-License-Identifier: MIT
            pragma solidity ^0.8.20;

            import "@openzeppelin/contracts/access/Ownable.sol";
            import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

            /**
             * @title  {project_name} Cross-Chain Module
             * @author {author}
             * @notice Generated by Polkadot XCM Wizard on {timestamp}
             * @dev    Implements XCM v3 message construction for Parachain {para_id}
             */
            contract {project_name.replace(" ", "")}Bridge is Ownable, ReentrancyGuard {{

                // --- CONFIGURATION ---
                uint32 public constant DESTINATION_PARA_ID = {para_id};
                address public constant XCM_PRECOMPILE = 0x0000000000000000000000000000000000000804;
                
                // --- EVENTS ---
                event BridgeInitiated(
                    address indexed user, 
                    uint256 amount, 
                    bytes32 indexed xcmHash
                );

                constructor() Ownable(msg.sender) {{}}

                /**
                 * @dev Bridges Native Assets to Target Parachain via XCM.
                 * Uses low-level bytes construction to ensure compatibility.
                 */
                function bridgeAssets(uint256 amount) external payable nonReentrant {{
                    require(msg.value >= amount, "Insufficient payment");

                    // 1. Construct MultiLocation (Parents: 1, Interior: X1)
                    bytes memory dest = abi.encodePacked(
                        uint8(1), 
                        uint8(1), 
                        uint32(DESTINATION_PARA_ID)
                    );

                    // 2. Construct Instruction (Withdraw -> Buy -> Deposit)
                    bytes memory message = abi.encodePacked(
                        uint8(2), amount,      // WithdrawAsset
                        uint8(0),              // AssetId: Native
                        uint8(5),              // DepositAsset
                        uint32(1), msg.sender  // Beneficiary
                    );

                    // 3. Execute via Precompile
                    (bool success, bytes memory data) = XCM_PRECOMPILE.call(
                        abi.encodeWithSignature("transact(bytes,bytes)", dest, message)
                    );
                    
                    require(success, "XCM Dispatch Error");
                    emit BridgeInitiated(msg.sender, amount, keccak256(message));
                }}
            }}
        """)

class XcmWizard:
    def __init__(self):
        self.clear_screen()
    
    def clear_screen(self):
        os.system('cls' if os.name == 'nt' else 'clear')

    def banner(self):
        print(Style.HEADER + Style.BOLD + r"""
   ___  ____  __    __ __  ____  ____  ____ 
  / __\/  _ \/ /   / //_//  _ \/  _ \/ __/
 / /_  / // / /__ / ,<  / /_/ / // / \ \  
/___/  \___/____//_/|_|/_/ /_/\___/\___/  
        """ + Style.RESET)
        print(f"{Style.BOLD} Polkadot Hub Infrastructure CLI v1.0.0{Style.RESET}")
        print(f"{Style.BLUE} --------------------------------------{Style.RESET}\n")

    def loading_bar(self, duration, message):
        """Menampilkan progress bar (Versi Aman Windows)"""
        print(f"{message}...")
        width = 40
        for i in range(width + 1):
            percent = int((i / width) * 100)
            # Menggunakan karakter ASCII (# dan -) agar tidak error di Windows
            bar = '#' * i + '-' * (width - i)
            sys.stdout.write(f"\r{Style.HEADER}|{bar}| {percent}%{Style.RESET}")
            sys.stdout.flush()
            time.sleep(duration / width)
        print("\n")

    def run(self):
        self.banner()
        
        try:
            Style.print_step(1, "PROJECT CONFIGURATION")
            p_name = input("      Project Name      : ") or "PolkaDefi"
            author = input("      Author (Developer): ") or "Dery"
            
            print("")
            Style.print_step(2, "NETWORK CONFIGURATION")
            Style.print_info("Common IDs: Moonbeam(2004), Acala(2000), Astar(2006)")
            para_id = input("      Target Parachain ID: ") or "2004"
            
            print("\n" + "-"*50 + "\n")
            
            # --- PROCESSING SECTION ---
            self.loading_bar(1.5, "Initializing XCM Environment")
            
            print(f"{Style.BLUE}[*] Calculating MultiLocation Paths...{Style.RESET}")
            time.sleep(0.5)
            print(f"{Style.BLUE}[*] Encoding ABI Instructions (WithdrawAsset, BuyExecution)...{Style.RESET}")
            time.sleep(0.5)
            
            # --- GENERATION SECTION ---
            filename = f"{p_name.replace(' ', '')}Bridge.sol"
            code = SolidityTemplates.get_xcm_contract(p_name, author, para_id)
            
            with open(filename, "w", encoding='utf-8') as f:
                f.write(code)
            
            # --- SUCCESS SECTION ---
            print("\n" + Style.GREEN + Style.BOLD + "? BUILD SUCCESSFUL" + Style.RESET)
            print(f"  Artifact : {Style.YELLOW}./{filename}{Style.RESET}")
            print(f"  Size     : {len(code)} bytes")
            print(f"  Network  : Polkadot Hub -> Parachain {para_id}")
            
            print("\n" + Style.BOLD + "Next Steps:" + Style.RESET)
            print("  1. Open this file in Remix IDE")
            print(f"  2. Deploy to Polkadot Hub")

        except KeyboardInterrupt:
            print(f"\n\n{Style.RED}? Process Aborted.{Style.RESET}")
            sys.exit(0)

if __name__ == "__main__":
    wizard = XcmWizard()
    wizard.run()